apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  selector:
    app: weather-app
    type: front-end
  ports:
    - protocol: TCP
      port: 80            # Exposed service port
      targetPort: 5000     # Container port
  type: NodePort
